# Generated by Django 2.0.6 on 2018-06-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20180629_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
