# Generated by Django 2.0.6 on 2018-07-01 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notifications_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ['-created_at']},
        ),
    ]
